disease_dic = {
    'Apple___Apple_scab': """ <b>Crop</b>- Apple <br/>Disease-- Apple Scab<br/> """,
    'Apple___Black_rot': """ <b>Crop</b>- Apple <br/>Disease-- Black Rot<br/> """,
    'Apple___Cedar_apple_rust': """ <b>Crop</b>- Apple <br/>Disease-- Cedar Apple Rust<br/> """,
    'Apple___healthy': """ <b>Crop</b>-- Apple <br/>Disease-- No disease<br/>""",
    'Blueberry___healthy': """ <b>Crop</b>-- Blueberry <br/>Disease-- No disease<br/>""",
    'Cherry_(including_sour)___Powdery_mildew': """ <b>Crop</b>-- Cherry <br/>Disease-- Powdery Mildew<br/>""",
    'Cherry_(including_sour)___healthy': """ <b>Crop</b>-- Cherry <br/>Disease-- No disease<br/>""",
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': """ <b>Crop</b>-- Corn <br/>Disease-- Grey Leaf Spot<br/>""",
    'Corn_(maize)___Common_rust_': """ <b>Crop</b>-- Corn(maize) <br/>Disease-- Common Rust<br/>""",
    'Corn_(maize)___Northern_Leaf_Blight': """ <b>Crop</b>-- Corn(maize) <br/>Disease-- Northern Leaf Blight<br/>""",
    'Grape___Black_rot': """ <b>Crop</b>-- Grape <br/>Disease-- Black Rot<br/>""",
    'Corn_(maize)___healthy': """ <b>Crop</b>-- Corn(maize) <br/>Disease-- No disease<br/>""",
    'Grape___Esca_(Black_Measles)': """ <b>Crop</b>-- Grape <br/>Disease-- Black Measles<br/>""",
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': """ <b>Crop</b>-- Grape <br/>Disease-- Leaf Blight<br/>""",
    'Grape___healthy': """ <b>Crop</b>-- Grape <br/>Disease-- No disease<br/>""",
    'Corn_(maize)___healthy': """ <b>Crop</b>-- Corn(maize) <br/>Disease-- No disease<br/>""",
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot': """<b> Crop</b> -- Grape <br/> Disease-- Leaf Spot""",
    'Orange___Haunglongbing_(Citrus_greening)': """ <b>Crop</b>-- Orange <br/>Disease-- Citrus Greening<br/>""",
    'Peach___Bacterial_spot': """ <b>Crop</b>-- Peach <br/>Disease-- Bacterial Spot<br/>""",
    'Pepper,_bell___Bacterial_spot': """ <b>Crop</b>-- Pepper <br/>Disease-- Bacterial Spot<br/>""",
    'Peach___healthy': """ <b>Crop</b>-- Peach <br/>Disease-- No disease<br/>""",
    'Pepper,_bell___healthy': """ <b>Crop</b>-- Pepper <br/>Disease-- No disease<br/>""",
    'Potato___healthy': """ <b>Crop</b>-- Potato <br/>Disease-- No disease<br/>""",
    'Raspberry___healthy': """ <b>Crop</b>-- Raspberry <br/>Disease-- No disease<br/>""",
    'Soybean___healthy': """ <b>Crop</b>-- Soyabean <br/>Disease-- No disease<br/>""",
    'Strawberry___healthy': """ <b>Crop</b>-- Strawberry <br/>Disease-- No disease<br/>""",
    'Tomato___healthy': """ <b>Crop</b>-- Tomato <br/>Disease-- No disease<br/>!""",
    'Potato___Early_blight': """ <b>Crop</b>-- Potato <br/>Disease-- Early Blight<br/>""",
    'Potato___Late_blight': """ <b>Crop</b>-- Potato <br/>Disease-- Late Blight<br/>""",
    'Squash___Powdery_mildew': """ <b>Crop</b>-- Squash <br/>Disease-- Powdery mildew<br/>""",
    'Strawberry___Leaf_scorch': """ <b>Crop</b>-- Strawberry <br/>Disease-- Leaf Scorch<br/>""",
    'Tomato___Bacterial_spot': """ <b>Crop</b>-- Tomato <br/>Disease-- Bacterial Spot<br/>""",
    'Tomato___Early_blight': """ <b>Crop</b>-- Tomato <br/>Disease-- Early Blight<br/>""",
    'Tomato___Late_blight': """ <b>Crop</b>-- Tomato <br/>Disease-- Late Blight<br/>""",
    'Tomato___Leaf_Mold': """ <b>Crop</b>-- Tomato <br/>Disease-- Leaf Mold<br/>.""",
    'Tomato___Septoria_leaf_spot': """ <b>Crop</b>-- Tomato <br/>Disease-- Leaf Spot<br/>""",
    'Tomato___Spider_mites Two-spotted_spider_mite': """ <b>Crop</b>-- Tomato <br/>Disease-- Two-spotted spider mite<br/>""",
    'Tomato___Target_Spo': """ <b>Crop</b>-- Tomato <br/>Disease-- Target Spot<br/>""",
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': """ <b>Crop</b>-- Tomato <br/>Disease-- Yellow Leaf Curl Virus<br/>""",
    'Tomato___Tomato_mosaic_virus': """ <b>Crop</b>-- Tomato <br/>Disease-- Mosaic Virus<br/>"""
}